# Generated by Django 5.2.16 on 2026-07-29 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nazoratchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nazoratchi',
                'verbose_name_plural': 'Nazoratchilar',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Talabgor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('ism', models.CharField(max_length=100, verbose_name='Ismi')),
                ('otasining_ismi', models.CharField(max_length=100, verbose_name='Otasining ismi')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('photo', models.ImageField(upload_to='talabgorlar/%Y/%m/', verbose_name='Rasm')),
                ('id_raqam', models.CharField(db_index=True, max_length=6, unique=True, verbose_name='ID raqam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nazoratchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talabgorlar', to='core.nazoratchi', verbose_name='Nazoratchi')),
            ],
            options={
                'verbose_name': 'Talabgor',
                'verbose_name_plural': 'Talabgorlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
